import mongoose from 'mongoose';
import dotenv from 'dotenv';
import crypto from 'crypto';
import { Bot } from 'cordia-shared';

dotenv.config();

const MONGO_URI = process.env.MONGO_URI || '';

if (!MONGO_URI) {
  console.error('MONGO_URI is missing from .env');
  process.exit(1);
}

const seed = async () => {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('✅ Connected to MongoDB for seeding');

    // Create a dummy developer
    const ownerId = '123456789012345678';
    const botId = '987654321098765432';
    
    // Generate an API Key (in a real app, this would be generated in the dashboard API)
    const apiKey = 'cordia_' + crypto.randomBytes(24).toString('hex');

    // Delete existing bot if it exists
    await Bot.deleteOne({ botId });

    // Create new Bot
    const bot = await Bot.create({
      botId,
      apiKey,
      ownerId,
      name: 'Cordia Test Bot',
      description: 'A test bot generated by the seed script',
      isPublic: true,
    });

    console.log('\n🎉 Seed successful! Use these credentials in your test script:');
    console.log('--------------------------------------------------');
    console.log(`Bot ID:  ${bot.botId}`);
    console.log(`API Key: ${bot.apiKey}`);
    console.log('--------------------------------------------------\n');

    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  }
};

seed();
